In [1]:
import requests
import lxml.html
from pypdf import PdfReader
import pandas as pd
import time
from google import genai
from pathlib import Path
from google.genai import types, errors
import os
import us
from datetime import datetime

from dotenv import load_dotenv, find_dotenv
from pydantic import BaseModel, Field
from typing import List, Optional, TypedDict, get_type_hints

In [2]:
case_df = pd.read_csv("../data/cases_scdb.csv")

In [3]:
# Manually enumerate rights here, but
# programmatically create dataframe columns with these names later
class RightsDict(BaseModel):
    environment: str = Field(
        description="The effect of the court's decision on environmental rights"
    )
    consumers: str = Field(description="The effect of the court's decision on consumer rights")
    reproductive_rights: str = Field(
        description="The effect of the court's decision on reproductive rights"
    )
    democratic_norms: str = Field(
        description="The effect of the court's decision on democratic norms"
    )
    free_press: str = Field(
        description="The effect of the court's decision on the right to free press"
    )
    public_health: str = Field(description="The effect of the court's decision on public health")
    separation_church_state: str = Field(
        description="The effect of the court's decision on separation of church and state"
    )
    voting_access: str = Field(description="The effect of the court's decision on voting rights")
    public_education: str = Field(
        description="The effect of the court's decision on the right to public education"
    )
    free_speech: str = Field(
        description="The effect of the court's decision on the right to free speech"
    )
    privacy: str = Field(description="The effect of the court's decision on privacy rights")
    worker_rights: str = Field(description="The effect of the court's decision on worker rights")


class IndividualOpinion(BaseModel):
    judge_name: str = Field(description="The full name of the judge giving an opinion.")
    ruling: str = Field(
        description='"concur" or "dissent" or "other" based on how this judge ruled,'
    )
    description: str = Field(
        description="An extremely brief description of the judge's own opinion on the case."
    )


class Case(BaseModel):
    issue_debate: str = Field(
        description='A phrase starting with "Whether" that summarizes '
        "the main issue being debated in the case"
    )
    plaintiff_argument: str = Field(
        description="Briefly, the plaintiff's stance on the debate issue"
    )
    defendant_argument: str = Field(
        description="Briefly, the defendant's stance on the debate issue"
    )
    decision_outcome: str = Field(
        description="The court's final decision for the case whether "
        "they ruled with the plaintiff or not."
    )
    decision_winner: str = Field(
        description='The party that the court sided with ("plaintiff","defendant","other").'
    )
    rights_affected: RightsDict
    judge_opinions: List[IndividualOpinion]

In [4]:
def read_opinion(pdf_link: str, model_id: str, client: genai.Client, prompt: str):
    """
    Inputs:
    - pdf_link: string
    - model_id: string
    - client: genai.Client
    - prompt: str

    Outputs:
    - dict

    Function makes a request to the content from a pdf url and prompts it into
    Gemini through the inputted gemini client. Returns a dictionary following
    the structure of the Case class defined outside of the function.

    If the LLM call runs into a server error due to high demand, the function
    waits between 5 seconds and 1 minute before trying again.
    """
    resp = requests.get(pdf_link).content
    wait_time = 5

    while True:
        try:
            genai_resp = client.models.generate_content(
                model=model_id,
                contents=[types.Part.from_bytes(data=resp, mime_type="application/pdf"), prompt],
                config={
                    "response_mime_type": "application/json",
                    "response_json_schema": Case.model_json_schema(),
                    "temperature": 0,
                },
            )
            return Case.model_validate_json(genai_resp.text).model_dump()

        except errors.ServerError as e:
            print("Ran into server error due to high demand")
            print(f"Waiting for {wait_time} seconds before calling again")
            time.sleep(wait_time)
            wait_time += 1

            if wait_time > 60:
                print("Wait time exceeds 1 minute")
                raise e

In [ ]:
'''
def read_opinion(pdf_link: str, model_id: str, client: genai.Client, prompt: str):
    """
    Inputs:
    - pdf_link: string
    - model_id: string
    - client: genai.Client
    - prompt: str

    Outputs:
    - dict

    Function makes a request to the content from a pdf url and prompts it into
    Gemini through the inputted gemini client. Returns a dictionary following
    the structure of the Case class defined outside of the function.

    If the LLM call runs into a server error due to high demand, the function
    waits between 5 seconds and 1 minute before trying again.
    """
    resp = requests.get(pdf_link).content
    wait_time = 5

    while True:
        try:
            genai_resp = client.models.generate_content(
                model=model_id,
                contents=[types.Part.from_bytes(data=resp, mime_type="application/pdf"), prompt],
                config=types.GenerateContentConfig(
                    response_mime_type="application/json",
                    response_json_schema=Case.model_json_schema(),
                    thinking_config=types.ThinkingConfig(thinking_level="medium"),
                ),
            )
            return Case.model_validate_json(genai_resp.text).model_dump()

        except errors.ServerError as e:
            print("Ran into server error due to high demand")
            print(f"Waiting for {wait_time} seconds before calling again")
            time.sleep(wait_time)
            wait_time += 1

            if wait_time > 300:
                print("Wait time exceeds 5 minutes")
                raise e
'''

In [5]:
def analyze_state_cases(case_df: pd.DataFrame, prompt_start: str, client_info: dict):
    """
    Inputs:
    - case_df: pd.Dataframe,
    - prompt_start: str,
    - client_info: dict

    Outputs:
    - file_dic: dict

    Function creates the full prompt by taking the prompt start (extracted)
    from .txt file and joins it with the string version of the judge
    dataframe. It then extract the information about the client, the model id
    and gemini client.
    """
    num_cases = len(case_df)
    model_id = client_info["model_id"]
    client = client_info["client"]

    file_dic = {}
    for i in range(num_cases):
        print(f"Querying case {i}")
        docket_no = case_df.iloc[i]["docket_no"].replace(" ", "-")
        state = case_df.iloc[i]["state"]
        date = str(datetime.strptime(case_df.iloc[i]["date"], "%B %d, %Y"))[:10].replace("-", "/")
        pdf_link = case_df.iloc[i]["opinion_link"]

        case_ref = "_".join([docket_no, state, date])

        opinion_resp = read_opinion(pdf_link, model_id, client, prompt_start)

        file_dic[case_ref] = {}
        file_dic[case_ref]["pdf_link"] = pdf_link
        file_dic[case_ref]["response"] = opinion_resp

    return file_dic

In [6]:
def apply_model(
    case_df: pd.DataFrame,
    prompt_path: str,
    model_id: str = "gemini-2.5-flash",
):
    """
    Inputs:
    - case_df: pd.Dataframe,
    - prompt_path: str,
    - model_id: str

    Outputs:
    - case_dic: dict

    This function extracts the fixed part of the prompt by reading the .txt
    file, and it initializes the Gemini model by using the API key. It then
    calls analyze_cases() returns its output.
    """
    with open(prompt_path, "r") as prompt_file:
        prompt_start = prompt_file.read()

    load_dotenv(find_dotenv())

    gemini_key = os.getenv("GEMINI_API_KEY")
    client_info = {"model_id": model_id, "client": genai.Client(api_key=gemini_key)}

    case_dic = analyze_state_cases(case_df, prompt_start, client_info)

    return case_dic

In [7]:
def state_opinion_table(case_dic: dict):
    """
    Inputs:
    - case_dic: dict (the output of apply_model())

    Outputs:
    - pd.DataFrame

    This function converst the output from apply_model() into an opinion
    table with three columns:
    - case_id
    - name
    - opinion
    """
    opinion_table = {"case_id": [], "name": [], "description": [], "ruling": []}

    for key in case_dic.keys():
        opinions = case_dic[key]["response"]
        num_opinions = len(opinions["judge_opinions"])

        for i in range(num_opinions):
            opinion_table["case_id"].append(key)

            judge_name = opinions["judge_opinions"][i]["judge_name"]
            opinion_table["name"].append(judge_name)

            description = opinions["judge_opinions"][i]["description"]
            opinion_table["description"].append(description)

            ruling = opinions["judge_opinions"][i]["ruling"]
            opinion_table["ruling"].append(ruling)

    return pd.DataFrame(opinion_table)

In [8]:
def state_case_table(case_df: pd.DataFrame, case_dic: dict):
    """
    Inputs:
    - case_df: pd.DataFrame
    - case_dic: dict

    Outputs:
    - pd.DataFrame

    This function takes a dataframe of cases, and compines it with the output
    of apply_model() to create a complete case table that includes case
    decisions and political dimensions.
    """
    case_table = {
        "case_id": [],
        "docket_no": [],
        "title": [],
        "state": [],
        "date": [],
        "type": [],
        "description": [],
        "plaintiff_argument": [],
        "defendant_argument": [],
        "decision_outcome": [],
        "decision_winner": [],
        # "decision_status": [],
    }
    rights_enumerated_list = list(get_type_hints(RightsDict).keys())
    rights_enumerated_dict = {right: [] for right in rights_enumerated_list}
    case_table = case_table | rights_enumerated_dict

    num_cases = len(case_df)

    for i in range(num_cases):
        docket_no = case_df.iloc[i]["docket_no"].replace(" ", "-")
        case_table["docket_no"].append(docket_no)
        state = case_df.iloc[i]["state"]
        case_table["state"].append(state)
        date = str(datetime.strptime(case_df.iloc[i]["date"], "%B %d, %Y"))[:10].replace("-", "/")
        case_table["date"].append(date)

        title = case_df.iloc[i]["title"]
        case_table["title"].append(title)
        type = case_df.iloc[i]["type"]
        case_table["type"].append(type)

        case_id = "_".join([docket_no, state, date])
        case_table["case_id"].append(case_id)

        response = case_dic[case_id]["response"]
        case_table["description"].append(response["issue_debate"])
        case_table["plaintiff_argument"].append(response["plaintiff_argument"])
        case_table["defendant_argument"].append(response["defendant_argument"])
        case_table["decision_outcome"].append(response["decision_outcome"])
        case_table["decision_winner"].append(response["decision_winner"])

        rights_affected = response["rights_affected"]
        for right in rights_enumerated_list:
            case_table[right].append(rights_affected[right])

        # status = ~case_df.iloc[i]["pending"]  # Negate, "not pending" means "decided"
        # case_table["decision_status"].append(status)

    return pd.DataFrame(case_table)

In [9]:
def produce_tables(
    case_df: pd.DataFrame,
    prompt_path: str = "../ingestion/prompt.txt",
    model_id: str = "gemini-2.5-flash",
):
    """
    Inputs:
    - case_df: pd.DataFrame
    - prompt_path: str

    Outputs:
    - rd: dict
    - llm_run_metadata: dict

    This function takes dataframes of cases and judges, and iterates state
    by state to iteratively create the opinion and case tables. Returns
    each in a dictionary.
    """
    states = case_df["state"].sort_values().unique()

    opinions = []
    cases = []

    for state in states:
        state_cases = case_df[case_df["state"] == state]

        case_dic = apply_model(state_cases, prompt_path, model_id)

        opinions.append(state_opinion_table(case_dic))
        cases.append(state_case_table(state_cases, case_dic))

    rd = {"individual_opinions": pd.concat(opinions), "case": pd.concat(cases)}

    # Also return JSON metadata on this LLM batch run
    with open(prompt_path, "r") as prompt_file:
        prompt = prompt_file.read()
    llm_run_metadata = {
        "timestamp": datetime.today(),
        "model_id": model_id,
        "cases_processed": rd["case"]["case_id"].tolist(),
        "prompt_start": prompt,
    }

    return rd, llm_run_metadata

In [10]:
test_df = case_df.sample(frac=1).reset_index(drop=True).head(5)
test_df

,docket_no,title,state,date,type,pending,opinion_link
0,23-1218,State v. Scullark,Iowa,"June 20, 2025",Criminal Law,False,https://statecourtreport.org/sites/default/fil...
1,2021-1403,DuBose v. McGuffey,Ohio,"January 4, 2022",Criminal Law,False,https://statecourtreport.org/sites/default/fil...
2,S-18292,Taylor v. Alaska Legislative Affairs Agency,Alaska,"May 26, 2023",Government Structure,False,https://statecourtreport.org/sites/default/fil...
3,S-1-SC-39225,Aztec Municipal Schools v. Cardenas,New Mexico,"April 1, 2024",Torts and Liability,False,https://statecourtreport.org/sites/default/fil...
4,89PA22,Fearrington v. City of Greenville,North Carolina,"May 23, 2024",Government Structure,False,https://statecourtreport.org/sites/default/fil...

In [11]:
# Using gemini-2.5-flash with temperature set to 0
tables_zero_temp, meta_data = produce_tables(test_df, prompt_path="prompt.txt")
display(tables_zero_temp["case"])
display(tables_zero_temp["individual_opinions"])

Querying case 0
Querying case 0
Querying case 0
Querying case 0
Querying case 0

,case_id,docket_no,title,state,date,type,description,plaintiff_argument,defendant_argument,decision_outcome,...,reproductive_rights,democratic_norms,free_press,public_health,separation_church_state,voting_access,public_education,free_speech,privacy,worker_rights
0,S-18292_Alaska_2023/05/26,S-18292,Taylor v. Alaska Legislative Affairs Agency,Alaska,2023/05/26,Government Structure,Whether the Alaska Constitution bars a lawsuit...,The Attorney General argued he had common law ...,The Legislative Affairs Agency argued that the...,The court affirmed the superior court's decisi...,...,NA,protected,NA,NA,NA,NA,NA,NA,NA,NA
0,23-1218_Iowa_2025/06/20,23-1218,State v. Scullark,Iowa,2025/06/20,Criminal Law,"Whether a search of a defendant's fanny pack, ...",The search of his fanny pack violated his cons...,The search was a valid search incident to arre...,The Supreme Court of Iowa vacated the court of...,...,NA,infringed,NA,NA,NA,NA,NA,NA,infringed,NA
0,S-1-SC-39225_New Mexico_2024/04/01,S-1-SC-39225,Aztec Municipal Schools v. Cardenas,New Mexico,2024/04/01,Torts and Liability,Whether the Workers' Compensation Act's provis...,The worker argues that the Act discriminates b...,The employer contends that workers with second...,The court concluded that Sections 52-1-41(C) a...,...,NA,protected,NA,NA,NA,NA,NA,NA,NA,protected
0,89PA22_North Carolina_2024/05/23,89PA22,Fearrington v. City of Greenville,North Carolina,2024/05/23,Government Structure,Whether the City of Greenville's Red Light Cam...,The plaintiffs argued that the RLCEP's funding...,The defendants argued that the Local Act statu...,The Supreme Court affirmed the plaintiffs' tax...,...,NA,NA,NA,NA,NA,NA,protected,NA,NA,NA
0,2021-1403_Ohio_2022/01/04,2021-1403,DuBose v. McGuffey,Ohio,2022/01/04,Criminal Law,"Whether the $1,500,000 bail set for Justin DuB...","DuBose argued that the $1,500,000 bail was exc...","The state argued that the $1,500,000 bail was ...",The court affirmed the judgment of the court o...,...,NA,infringed,NA,NA,NA,NA,NA,NA,NA,NA

,case_id,name,description,ruling
0,S-18292_Alaska_2023/05/26,Winfree,"Concurred, argued that the Attorney General's ...",concur
1,S-18292_Alaska_2023/05/26,Maassen,Concurred with majority opinion.,concur
2,S-18292_Alaska_2023/05/26,Carney,Concurred with majority opinion.,concur
3,S-18292_Alaska_2023/05/26,Borghesan,Concurred with majority opinion.,concur
4,S-18292_Alaska_2023/05/26,Henderson,Concurred with majority opinion.,concur
0,23-1218_Iowa_2025/06/20,"Oxley, J.","Concurred, argued that the search of the fanny...",concur
1,23-1218_Iowa_2025/06/20,"McDermott, J.","Dissented, argued that the search was unlawful...",dissent
0,S-1-SC-39225_New Mexico_2024/04/01,Jane B. Yohalem,"Concurred, arguing that the Workers' Compensat...",concur
1,S-1-SC-39225_New Mexico_2024/04/01,J. Miles Hanisee,Concurred with majority opinion.,concur
2,S-1-SC-39225_New Mexico_2024/04/01,Gerald E. Baca,Concurred with majority opinion.,concur
0,89PA22_North Carolina_2024/05/23,"Earls, Justice","Concurred, argued that the Local Act and Inter...",concur
1,89PA22_North Carolina_2024/05/23,"Dietz, Justice",Did not participate in the consideration or de...,other
2,89PA22_North Carolina_2024/05/23,"Berger, Justice","Dissented, argued that the majority failed to ...",dissent
0,2021-1403_Ohio_2022/01/04,"O'Connor, C.J.",Concurred with majority opinion.,concur
1,2021-1403_Ohio_2022/01/04,"Stewart, J.",Concurred with majority opinion.,concur
2,2021-1403_Ohio_2022/01/04,"Brunner, J.",Concurred with majority opinion.,concur
3,2021-1403_Ohio_2022/01/04,"Donnelly, J.","Concurred, argued that the issue is not a spec...",concur
4,2021-1403_Ohio_2022/01/04,"Kennedy, J.","Dissented, argued that DuBose failed to prove ...",dissent
5,2021-1403_Ohio_2022/01/04,"Fischer, J.","Dissented, argued that abuse of discretion is ...",dissent
6,2021-1403_Ohio_2022/01/04,"DeWine, J.","Dissented, argued that the majority's decision...",dissent

In [13]:
# Using gemini-3-flash-preview with medium-level thinking
tables_medium_think, meta_data = produce_tables(
    test_df, model_id="gemini-3-flash-preview", prompt_path="prompt.txt"
)
display(tables_medium_think["case"])
display(tables_medium_think["individual_opinions"])

Querying case 0
Querying case 0
Querying case 0
Querying case 0
Querying case 0

,case_id,docket_no,title,state,date,type,description,plaintiff_argument,defendant_argument,decision_outcome,...,reproductive_rights,democratic_norms,free_press,public_health,separation_church_state,voting_access,public_education,free_speech,privacy,worker_rights
0,S-18292_Alaska_2023/05/26,S-18292,Taylor v. Alaska Legislative Affairs Agency,Alaska,2023/05/26,Government Structure,"Whether the Alaska Constitution's Article III,...",The Attorney General argued that he possesses ...,The Legislative Affairs Agency argued that the...,The court affirmed that the lawsuit was consti...,...,NA,protected,NA,NA,NA,NA,NA,NA,NA,NA
0,23-1218_Iowa_2025/06/20,23-1218,State v. Scullark,Iowa,2025/06/20,Criminal Law,Whether the warrantless search of a fanny pack...,The State argued the search was a valid search...,The defendant argued that the search violated ...,The court vacated the court of appeals decisio...,...,NA,NA,NA,NA,NA,NA,NA,NA,infringed,NA
0,S-1-SC-39225_New Mexico_2024/04/01,S-1-SC-39225,Aztec Municipal Schools v. Cardenas,New Mexico,2024/04/01,Torts and Liability,Whether the Workers' Compensation Act violates...,The plaintiff argued that the statutory limits...,The defendant argued that workers with mental ...,The court ruled that the challenged statutory ...,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,protected
0,89PA22_North Carolina_2024/05/23,89PA22,Fearrington v. City of Greenville,North Carolina,2024/05/23,Government Structure,Whether the City of Greenville's red light cam...,The plaintiffs argued that the cost-sharing ag...,The defendants argued that the funding arrange...,The court affirmed that the plaintiffs had sta...,...,NA,protected,NA,NA,NA,NA,infringed,NA,NA,NA
0,2021-1403_Ohio_2022/01/04,2021-1403,DuBose v. McGuffey,Ohio,2022/01/04,Criminal Law,Whether a $1.5 million bail amount was unconst...,The bail was excessive because it exceeded the...,The bail amount was justified by the serious n...,"The court affirmed the lower court's decision,...",...,NA,protected,NA,NA,NA,NA,NA,NA,NA,NA

,case_id,name,description,ruling
0,S-18292_Alaska_2023/05/26,Daniel Winfree,"Concurred, argued that the suit was constituti...",concur
1,S-18292_Alaska_2023/05/26,Peter Maassen,Concurred with majority opinion,concur
2,S-18292_Alaska_2023/05/26,Susan M. Carney,Concurred with majority opinion,concur
3,S-18292_Alaska_2023/05/26,Dario Borghesan,Concurred with majority opinion,concur
4,S-18292_Alaska_2023/05/26,Jennifer S. Henderson,Concurred with majority opinion,concur
0,23-1218_Iowa_2025/06/20,Oxley,"Concurred, argued that because the fanny pack ...",concur
1,23-1218_Iowa_2025/06/20,McDermott,"Dissented, argued that the search was unconsti...",dissent
0,S-1-SC-39225_New Mexico_2024/04/01,Jane B. Yohalem,"Concurred, argued that the Act's disparate tre...",concur
1,S-1-SC-39225_New Mexico_2024/04/01,J. Miles Hanisee,Concurred with majority opinion,concur
2,S-1-SC-39225_New Mexico_2024/04/01,Gerald E. Baca,Concurred with majority opinion,concur
0,89PA22_North Carolina_2024/05/23,Anita Earls,"Concurred, argued that the Fines and Forfeitur...",concur
1,89PA22_North Carolina_2024/05/23,Phil Berger,"Dissented, argued that the North Carolina Cons...",dissent
2,89PA22_North Carolina_2024/05/23,Richard Dietz,"Other, did not participate in the consideratio...",other
0,2021-1403_Ohio_2022/01/04,Maureen O'Connor,Concurred with majority opinion.,concur
1,2021-1403_Ohio_2022/01/04,Melody J. Stewart,Concurred with majority opinion.,concur
2,2021-1403_Ohio_2022/01/04,Jennifer Brunner,Concurred with majority opinion.,concur
3,2021-1403_Ohio_2022/01/04,Michael P. Donnelly,"Concurred, argued that judges should not set b...",concur
4,2021-1403_Ohio_2022/01/04,Sharon L. Kennedy,"Dissented, argued that the defendant failed to...",dissent
5,2021-1403_Ohio_2022/01/04,Patrick F. Fischer,"Dissented, argued that the appellate court sho...",dissent
6,2021-1403_Ohio_2022/01/04,Pat DeWine,"Dissented, argued that the ruling improperly l...",dissent