In [ ]:
import requests
import lxml.html
from pypdf import PdfReader
import pandas as pd
from google import genai
from pathlib import Path
from google.genai import types
import os

from dotenv import load_dotenv, find_dotenv
from pydantic import BaseModel, Field
from typing import List, Optional

from ingest_sc_cases import case_df
from ingest_sc_judges import judge_pd

In [25]:
# Cases with no opinion documents
case_df[~case_df["opinion_link"].str.contains("statecourt", na=False)]

,docket_no,title,state,date,type,pending,opinion_link
11,2026-00384,Williams v. Board of Elections of the State of...,New York,"March 19, 2026",Voting Rights and Elections,False,None
35,20220896,State v. Andrus,Utah,"August 7, 2025",Criminal Law,False,None
47,S-1-SC-40715,Franklin v. Martinez,New Mexico,"January 26, 2026",Criminal Law,False,None
88,22 OC 00022 1 B,Persaud-Zamora v. Cegavske,Nevada,"April 26, 2022",Voting Rights and Elections,False,None
101,EF2025-2536,Texas v. Bruck,Texas,"October 31, 2025",Reproductive Rights,False,None
103,2025AP002121,Voces de la Frontera v. Gerber,Wisconsin,"September 18, 2025",Government Structure,False,None
120,PR-123179,McVay v. Cockroft,Oklahoma,"July 28, 2025",Voting Rights and Elections,False,None
152,15-25-00093-CV,State v. City of San Antonio,Texas,"June 19, 2025",Reproductive Rights,False,None
207,CV01-23-14744,Adkins v. State,Idaho,"April 11, 2025",Reproductive Rights,False,None
228,SJC-13666,Gotay v. Creen,Massachusetts,"March 21, 2025",Civil Due Process,False,None
229,471-08943-2024,Texas v. Margaret Daley Carpenter,Texas,"February 13, 2025",Reproductive Rights,False,None
231,CV2024-034624,Reuss v. Arizona,Arizona,"March 5, 2025",Reproductive Rights,False,None
264,24-0884,In re Texas House of Representatives,Texas,"November 15, 2024",Criminal Law,False,None
285,SC-2023-0601,Ex parte Jackson Hospital & Clinic,Alabama,"October 4, 2024",Criminal Law,False,None
299,S-24-563,State ex rel. Spung v. Evnen,Nebraska,"October 16, 2024",Criminal Law,False,None
304,CV-24-0180-AP/EL,Arizona Right to Life v. Fontes,Arizona,"August 20, 2024",Reproductive Rights,False,None
324,A-23-876702-W,Silver State Hope Fund v. Nevada Department of...,Nevada,"August 8, 2024",Reproductive Rights,False,None
331,2024-0161,State ex rel. Dudley v. Yost,Ohio,"October 30, 2024",Election 2024,False,None
362,1CCV-24-0000269,Navahine F. v. Hawaii Department of Transporta...,Hawaii,"June 20, 2024",Environment,False,None
386,23-0727,Antoun v. Antoun,Texas,"June 14, 2024",Reproductive Rights,False,None
412,88263,Fair Maps Nevada v. Jeng,Nevada,"May 10, 2024",Election 2024,False,None

In [33]:
class Opinion(BaseModel):
    judge_name: str = Field(description="The full name of the judge giving an opinion.")
    opinion_summary: str = Field(
        description="An extremely brief description of the judge's opinion on the case."
    )


class Case(BaseModel):
    title: str = Field(description="The title of the case.")
    decision: str = Field(description="The final decision that was made for the case.")
    issue_debate: str = Field(description="The main issue being debated in the case.")
    judge_opinions: List[Opinion]

In [34]:
def read_opinion(pdf_link: str, model_id: str, client: genai.Client, prompt: str):
    resp = requests.get(pdf_link).content

    genai_resp = client.models.generate_content(
        model=model_id,
        contents=[types.Part.from_bytes(data=resp, mime_type="application/pdf"), prompt],
        config={
            "response_mime_type": "application/json",
            "response_json_schema": Case.model_json_schema(),
        },
    )

    return Case.model_validate_json(genai_resp.text)

In [ ]:
def analyze_state_cases(
    case_df: pd.DataFrame, judge_df: pd.DataFrame, prompt_start: str, client_info: dict
):
    prompt = prompt_start + "$DATAFRAME$" + judge_df.to_markdown(index=False)
    num_cases = len(case_df)
    model_id = client_info["model_id"]
    client = client_info["client"]

    file_dic = {}
    for i in range(num_cases):
        print(f"Querying case {i}")
        docket_no = case_df.iloc[i]["docket_no"].replace(" ", "-")
        state = case_df.iloc[i]["state"]
        date = case_df.iloc[i]["date"].replace(" ", "-")
        pdf_link = case_df.iloc[i]["opinion_link"]

        case_ref = "_".join([docket_no, state, date])

        opinion_resp = read_opinion(pdf_link, model_id, client, prompt)

        file_dic[case_ref] = {}
        file_dic[case_ref]["pdf_link"] = pdf_link
        file_dic[case_ref]["response"] = opinion_resp

    return file_dic

In [39]:
with open("prompt.txt", "r") as prompt_file:
    prompt_start = prompt_file.read()

load_dotenv(find_dotenv())

gemini_key = os.getenv("GEMINI_API_KEY")
client_info = {"model_id": "gemini-2.5-flash-lite", "client": genai.Client(api_key=gemini_key)}

lou_cases = case_df[case_df["state"] == "Louisiana"].head(5)
lou_judges = judge_pd[judge_pd["state"] == "LA"]

file_dic = analyze_state_cases(lou_cases, lou_judges, prompt_start, client_info)

Querying case 0
Querying case 1
Querying case 2
Querying case 3
Querying case 4

In [40]:
for key in file_dic.keys():
    print(f"Individual opinions for {key}")
    print(file_dic[key]["response"])

Individual opinions for 2025-O-00879_Louisiana_October-24,-2025
title='IN RE: JUDGE JENNIFER M. MEDLEY' decision='Judge Jennifer M. Medley is suspended for thirty days without pay and must reimburse the Commission $2,747.41 in costs.' issue_debate="The issue is whether Judge Medley's campaign activities, including false statements and unreported expenditures, violated judicial conduct rules and state law, with the defense arguing First Amendment protection for political speech versus the prosecution arguing for sanctions due to knowing falsehoods and misconduct." judge_opinions=[Opinion(judge_name='Cade Cole', opinion_summary='Not available'), Opinion(judge_name='Jay B. McCallum', opinion_summary='Not available'), Opinion(judge_name='Jefferson D. Hughes III', opinion_summary='Not available'), Opinion(judge_name='John Guidry', opinion_summary='Not available'), Opinion(judge_name='John L. Weimer', opinion_summary='Agrees with the majority findings related to dismissing Count I but finding a violation of Count II because Judge Medley knowingly made false statements that satisfies strict scrutiny in the Count II matter.'), Opinion(judge_name='Piper D. Griffin', opinion_summary='Not available')]
Individual opinions for 2024-KK-00737_Louisiana_May-9,-2025
title='STATE OF LOUISIANA VS. DAVIEONTRAY LEE BREAUX' decision='REVERSED AND REMANDED' issue_debate='The main issue is whether prosecutors may join capital felony charges with other felony charges, with the pro-position arguing for joinder and the con-position arguing against it.' judge_opinions=[Opinion(judge_name='Piper D. Griffin', opinion_summary='Granted writ to determine if prosecutors may join capital felony charges with other felony charges, holding they cannot.'), Opinion(judge_name='Jefferson D. Hughes III', opinion_summary='Concurs, stating death penalty cases have a different jury selection and penalty determination process, making the mode of trial different.'), Opinion(judge_name='Jay B. McCallum', opinion_summary="Dissents, arguing that the majority's conclusion is incorrect and that joint trials of capital and non-capital offenses would impose an intolerable administrative burden."), Opinion(judge_name='Cade Cole', opinion_summary="Concurs in the result, agreeing that capital and non-capital offenses cannot be joined, but argues the majority's constitutional analysis is dicta and the result is dictated by statutory law.")]
Individual opinions for 2024-CA-00995,-2024-CA-00996_Louisiana_March-21,-2025
title='Fremin v. Boyd Racing, LLC, La. 2024-CA-00995' decision="The court affirmed the lower court's judgment, declaring Act 437 unconstitutional because it allows historical horse racing without voter approval." issue_debate="The issue is whether Act 437, which legalized historical horse racing, is unconstitutional for not requiring voter approval, with plaintiffs arguing it's a new form of gaming requiring approval, and defendants arguing it's a form of pari-mutuel wagering not requiring new approval." judge_opinions=[Opinion(judge_name='Jeanette Theriot Knoll', opinion_summary='Heard the case as Justice Pro Tempore and participated in the decision.'), Opinion(judge_name='Cade Cole', opinion_summary='Not available'), Opinion(judge_name='Jay B. McCallum', opinion_summary='Not available'), Opinion(judge_name='Jefferson D. Hughes III', opinion_summary='Not available'), Opinion(judge_name='John Guidry', opinion_summary='Not available'), Opinion(judge_name='John L. Weimer', opinion_summary='Not available'), Opinion(judge_name='Piper D. Griffin', opinion_summary='Not available')]
Individual opinions for 2024-CC-00899_Louisiana_March-21,-2025
title='Welch v. United Med. Health We St-New Orleans LLC' decision="The trial court's denial of Welch's motion to declare La. R.S. 29:771(B)(2)(c)(i) unconstitutional is affirmed." issue_debate='The issue debated is whether La. R.S. 29:771(B)(2)(c)(i), which limits civil liability of healthcare providers during a public health emergency to gross negligence or willful misconduct, is constitutional. The pro-position argues the statute is constitutional and rationally related to a legitimate state interest. The con-position argues the statute is unconstitutional, violates due process, is a special law, and is overbroad.' judge_opinions=[Opinion(judge_name='Cade Cole', opinion_summary='Not available'), Opinion(judge_name='Jay B. McCallum', opinion_summary='Not available'), Opinion(judge_name='Jefferson D. Hughes III', opinion_summary='Not available'), Opinion(judge_name='John Guidry', opinion_summary='Not available'), Opinion(judge_name='John L. Weimer', opinion_summary='Not available'), Opinion(judge_name='Piper D. Griffin', opinion_summary="Dissents, arguing the statute is not applicable to the plaintiff's claim because the injuries were not related to the public health emergency and the plain language leads to absurd results.")]
Individual opinions for 2024-CD-00359_Louisiana_October-25,-2024
title='Theresa Fisher v. Steven Harter, Jr., et al.' decision='REVERSED; REMANDED WITH INSTRUCTIONS.' issue_debate="The issue is whether La. R.S. 13:4163, which grants peremptory grounds for continuance to legislators, unconstitutionally usurps the judiciary's power to manage its docket. The pro-position is that the statute is unconstitutional and infringes on judicial power, while the con-position is that the statute is a valid legislative act and should be upheld or interpreted narrowly." judge_opinions=[Opinion(judge_name='Jefferson D. Hughes III', opinion_summary="Reversed the district court's denial of the plaintiff's motion for declaratory judgment, declaring La. R.S. 13:4163 unconstitutional on its face, and remanded with instructions to conduct a contradictory hearing."), Opinion(judge_name='John L. Weimer', opinion_summary="Additionally concurs, finding the statute unconstitutional on its face as it eliminates judicial discretion and intrudes on the judiciary's inherent powers."), Opinion(judge_name='Jay B. McCallum', opinion_summary='Dissents, arguing that the majority used a "chainsaw" instead of a "scalpel" to remedy the issue, and that the legislature has the power to enact such laws.')]

In [44]:
opinion_table = {"opinion_id": [], "name": [], "opinion": []}

for key in file_dic.keys():
    opinions = file_dic[key]["response"].model_dump()
    num_opinions = len(opinions["judge_opinions"])

    for i in range(num_opinions):
        opinion_table["opinion_id"].append(key)
        opinion_table["name"].append(opinions["judge_opinions"][i]["judge_name"])
        opinion_table["opinion"].append(opinions["judge_opinions"][i]["opinion_summary"])

opinion_pd = pd.DataFrame(opinion_table)
opinion_pd

,opinion_id,name,opinion
0,"2025-O-00879_Louisiana_October-24,-2025",Cade Cole,Not available
1,"2025-O-00879_Louisiana_October-24,-2025",Jay B. McCallum,Not available
2,"2025-O-00879_Louisiana_October-24,-2025",Jefferson D. Hughes III,Not available
3,"2025-O-00879_Louisiana_October-24,-2025",John Guidry,Not available
4,"2025-O-00879_Louisiana_October-24,-2025",John L. Weimer,Agrees with the majority findings related to d...
5,"2025-O-00879_Louisiana_October-24,-2025",Piper D. Griffin,Not available
6,"2024-KK-00737_Louisiana_May-9,-2025",Piper D. Griffin,Granted writ to determine if prosecutors may j...
7,"2024-KK-00737_Louisiana_May-9,-2025",Jefferson D. Hughes III,"Concurs, stating death penalty cases have a di..."
8,"2024-KK-00737_Louisiana_May-9,-2025",Jay B. McCallum,"Dissents, arguing that the majority's conclusi..."
9,"2024-KK-00737_Louisiana_May-9,-2025",Cade Cole,"Concurs in the result, agreeing that capital a..."
10,"2024-CA-00995,-2024-CA-00996_Louisiana_March-2...",Jeanette Theriot Knoll,Heard the case as Justice Pro Tempore and part...
11,"2024-CA-00995,-2024-CA-00996_Louisiana_March-2...",Cade Cole,Not available
12,"2024-CA-00995,-2024-CA-00996_Louisiana_March-2...",Jay B. McCallum,Not available
13,"2024-CA-00995,-2024-CA-00996_Louisiana_March-2...",Jefferson D. Hughes III,Not available
14,"2024-CA-00995,-2024-CA-00996_Louisiana_March-2...",John Guidry,Not available
15,"2024-CA-00995,-2024-CA-00996_Louisiana_March-2...",John L. Weimer,Not available
16,"2024-CA-00995,-2024-CA-00996_Louisiana_March-2...",Piper D. Griffin,Not available
17,"2024-CC-00899_Louisiana_March-21,-2025",Cade Cole,Not available
18,"2024-CC-00899_Louisiana_March-21,-2025",Jay B. McCallum,Not available
19,"2024-CC-00899_Louisiana_March-21,-2025",Jefferson D. Hughes III,Not available
20,"2024-CC-00899_Louisiana_March-21,-2025",John Guidry,Not available
21,"2024-CC-00899_Louisiana_March-21,-2025",John L. Weimer,Not available
22,"2024-CC-00899_Louisiana_March-21,-2025",Piper D. Griffin,"Dissents, arguing the statute is not applicabl..."
23,"2024-CD-00359_Louisiana_October-25,-2024",Jefferson D. Hughes III,Reversed the district court's denial of the pl...
24,"2024-CD-00359_Louisiana_October-25,-2024",John L. Weimer,"Additionally concurs, finding the statute unco..."
25,"2024-CD-00359_Louisiana_October-25,-2024",Jay B. McCallum,"Dissents, arguing that the majority used a ""ch..."