In [8]:
import lxml.html
import requests
import time
import uuid
import pandas as pd

In [10]:
def make_request(url):
    user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
    acc = "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
    headers = {
        "User-Agent": user_agent,
        "Accept": acc,
        "Accept-Language": "en-US,en;q=0.5",
        "Accept-Encoding": "gzip, deflate",
        "Connection": "keep-alive",
    }

    resp = requests.get(url, headers=headers)

    if resp.status_code == 429:
        time.sleep(2.5)
        resp = make_request(url)
    elif resp.status_code == 200:
        return resp

In [11]:
def scrape_judge(url):
    j_page = lxml.html.fromstring(make_request(url).text)
    r_d = {}

    xp1 = "//div[@class = 'judge-info']//div[@class = 'about-list']"
    xp2 = "//div[@class = 'about-list-item']//h3/text()"
    item_titles = j_page.xpath(xp1 + xp2)

    xp1 = "//div[@class = 'judge-info']//div[@class = 'about-list']"
    xp2 = "//div[@class = 'about-list-item']//p/text()"
    items = j_page.xpath(xp1 + xp2)

    for i, title in enumerate(item_titles):
        r_d[title.lower()] = items[i].replace("\t", "").strip().lower()

    return r_d

In [16]:
def scrape_main(url):
    main_page = lxml.html.fromstring(make_request(url).text)

    xp1 = "//section[@filter = 'judge']//"
    xp2 = "a[contains(@href, 'judge')]//@href"
    judge_links = main_page.xpath(xp1 + xp2)

    xp1 = "//section[@filter = 'judge']//a[contains(@href, 'judge')]//"
    xp2 = "div[@class = 'module--content module--content-post']"
    xp3 = "//h2[@class = 'title']/text()"
    judge_names = main_page.xpath(xp1 + xp2 + xp3)

    xp1 = "//div[@class = 'about-icons']"
    xp2 = "//div[@class = 'about-icon' and @data-type = 'state']"
    xp3 = "//span[not(contains(@class, 'sr-only'))]/text()"
    judge_states = main_page.xpath(xp1 + xp2 + xp3)

    judge_fields = [
        "gender",
        "party",
        "race",
        "professional experience",
        "election type",
        "term start",
        "term end",
        "next election date",
    ]

    judge_pd = {"JID": [], "name": [], "state": []}

    for field in judge_fields:
        judge_pd[field] = []

    for i, name in enumerate(judge_names):
        judge_pd["name"].append(name)
        judge_pd["JID"].append(uuid.uuid4())
        judge_pd["state"].append(judge_states[i])

        judge_dic = scrape_judge(judge_links[i])
        print(f"Scraped judge: {name}")

        if judge_dic == {}:
            break

        for field in judge_fields:
            if field not in judge_dic:
                data = pd.NA
            else:
                data = judge_dic[field]

            judge_pd[field].append(data)

    return pd.DataFrame(judge_pd)

In [17]:
url = "https://state-law-research.org/state-justices/"

judge_pd = scrape_main(url)
judge_pd

Scraped judge: Abigail LeGrow
Scraped judge: Adam Tanenbaum
Scraped judge: Aimee A. Oravec
Scraped judge: Alisa Kelli Wise
Scraped judge: Allison Riggs
Scraped judge: Andrew J. McDonald
Scraped judge: Andrew M. Horton
Scraped judge: Andrew M. Mead
Scraped judge: Andrew Pinson
Scraped judge: Angela M. Eaves
Scraped judge: Angela McCormick Bisig
Scraped judge: Anita Earls
Scraped judge: Ann A. Scott Timmer
Scraped judge: Anna Blackburne-Rigsby
Scraped judge: Anne K. McKeig
Scraped judge: Anne M. Patterson
Scraped judge: Annette Kingsland
  Ziegler
Scraped judge: Anthony Cannataro
Scraped judge: Aruna Masih
Scraped judge: Barbara A. Madsen
Scraped judge: Barbara Webb
Scraped judge: Benjamin A. Land
Scraped judge: Bert Richardson
Scraped judge: Beth Baker
Scraped judge: Brady E. Mendheim, Jr.
Scraped judge: Brett Busby
Scraped judge: Brian D. Boatright
Scraped judge: Brian Hagedorn
Scraped judge: Brian K. Zahra
Scraped judge: Briana Zamora
Scraped judge: Bronson James
Scraped judge: Bryan K. Gould
Scraped judge: Brynja M. Booth
Scraped judge: C. Shannon Bacon
Scraped judge: Cade Cole
Scraped judge: Caitlin Halligan
Scraped judge: Caleb Stegall
Scraped judge: Carla Wong McMillian
Scraped judge: Carlos A. Samour, Jr.
Scraped judge: Carlos G. Muñiz
Scraped judge: Carol A. Corrigan
Scraped judge: Catharine F. Easterly
Scraped judge: Catherine R. Connors
Scraped judge: Charles J. Bethel
Scraped judge: Charles Trump
Scraped judge: Charles W. Johnson
Scraped judge: Chris Garrett
Scraped judge: Chris McCool
Scraped judge: Christina Nolan
Scraped judge: Christine Donohue
Scraped judge: Christopher M Goff
Scraped judge: Christopher McDonald
Scraped judge: Christopher Shea Nickell
Scraped judge: Cleo E. Powell
Scraped judge: Clint Bolick
Scraped judge: Colleen D. Zahn
Scraped judge: Colleen Melody
Scraped judge: Collins J. Seitz, Jr.
Scraped judge: Corinne A. Beckwith
Scraped judge: Cory Swanson
Scraped judge: Courtney Rae Hudson
Scraped judge: Cynthia Meyer
Scraped judge: D. Arthur Kelsey
Scraped judge: D. Garrison Hill
Scraped judge: Dalila Argaez Wendlandt
Scraped judge: Dan Biles
Scraped judge: Dan Hawkins
Scraped judge: Dana Kuehn
Scraped judge: Dana Oxley
Scraped judge: Daniel E. Will
Scraped judge: Daniel J. Crothers
Scraped judge: Daniel McCaffery
Scraped judge: Dario Borghesan
Scraped judge: David K. Overstreet
Scraped judge: David K. Thomson
Scraped judge: David Lewis
Scraped judge: David M. Ishee
Scraped judge: David N. May
Scraped judge: David N. Wecht
Scraped judge: David Newell
Scraped judge: David Schneck
Scraped judge: David Sullivan
Scraped judge: Debra Hembree Lambert
Scraped judge: Debra L. Stephens
Scraped judge: Debra Lehrmann
Scraped judge: Debra Todd
Scraped judge: Derek Molter
Scraped judge: Derek Vaughn
Scraped judge: Diana Hagen*
Scraped judge: Douglas Bahr
Scraped judge: Douglas Fasciale
Scraped judge: Douglas Herndon
Scraped judge: Douglas L. Combs
Scraped judge: Dustin P. Rowe
Scraped judge: Dwight Tarwater
Scraped judge: Edward M. Mansfield
Scraped judge: Elissa F. Cadish
Scraped judge: Elizabeth “Bessie” Dewar
Scraped judge: Elizabeth M. Welch
Scraped judge: Elizabeth Rochford
Scraped judge: Elizabeth T. Clement
Scraped judge: Eric S. Rosen
Scraped judge: Erin Lynch Prata
Scraped judge: Evan Young
Scraped judge: Fabiana Pierre-Louis
Scraped judge: Frank M. Gaziano
Scraped judge: G. Helen Whitener
Scraped judge: G. Richard Bevan
Scraped judge: Gabrielle Wolohojian
Scraped judge: Gary F. Traynor
Scraped judge: Gary Lumpkin
Scraped judge: Geoffrey G Slaughter
Scraped judge: George C. James, Jr.
Scraped judge: Gerald Titus
Scraped judge: Gina Parker
Scraped judge: Ginger Gooch
Scraped judge: Goodwin H. Liu
Scraped judge: Gordon J. MacDonald
Scraped judge: Gordon Moore
Scraped judge: Greg Cook
Scraped judge: Greg Shaw
Scraped judge: Gregory T. D’Auria
Scraped judge: Gregory W. Moeller
Scraped judge: Haley Bunn
Scraped judge: Harold E. Eaton, Jr.
Scraped judge: Holly Kirby
Scraped judge: Ingrid Gustafson
Scraped judge: J. Cody Hiland
Scraped judge: James A. Rice
Scraped judge: James D. Maxwell II
Scraped judge: James E. Edmondson
Scraped judge: James Jeremiah Shea
Scraped judge: James P. Beene
Scraped judge: James P. Sullivan
Scraped judge: James R. Winchester
Scraped judge: Jamie R. Grosshans
Scraped judge: Jane Bland
Scraped judge: Janet Protasiewicz
Scraped judge: Jason M. Bergevin
Scraped judge: Jay B. McCallum
Scraped judge: Jefferson D. Hughes III
Scraped judge: Jeffrey J. Funke
Scraped judge: Jeffrey S. Bivins
Scraped judge: Jenifer Branning
Scraped judge: Jennifer Brunner
Scraped judge: Jennifer S. Henderson
Scraped judge: Jenny Rivera
Scraped judge: Jerod Tufte
Scraped judge: Jesse F McClure, III
Scraped judge: Jill J. Karofsky
Scraped judge: Jill Pohlman
Scraped judge: Jimmy Blacklock
Scraped judge: John Cannon Few
Scraped judge: John D. Couriel
Scraped judge: John G. Fenn
Scraped judge: John Guidry
Scraped judge: John J. Ellington
Scraped judge: John Jay Hoffman
Scraped judge: John L. Weimer
Scraped judge: John Nielsen
Scraped judge: John P. Howard III
Scraped judge: John Phillip Devine
Scraped judge: John R. Freudenberg
Scraped judge: John R. Lopez IV
Scraped judge: John W. Kittredge
Scraped judge: Jon J. Jensen
Scraped judge: Jonathan Biran
Scraped judge: Jonathan J. Papik
Scraped judge: Jorge Labarga
Scraped judge: Joseph Deters
Scraped judge: Joshua Deahl
Scraped judge: Joshua P. Groban
Scraped judge: Josiah Dennis Coleman
Scraped judge: Joy V. Cunningham
Scraped judge: Jude Pate
Scraped judge: Julia M. Lipez
Scraped judge: Julie J. Vargas
Scraped judge: Junius P. Fulton III
Scraped judge: Karen L. Valihura
Scraped judge: Karen R. Baker
Scraped judge: Kari Gray
Scraped judge: Karl Procaccini
Scraped judge: Kate M. Fox
Scraped judge: Katherine Biidegaray
Scraped judge: Kathryn H. King
Scraped judge: Kelli Evans
Scraped judge: Kelly C. Broniec
Scraped judge: Kelly Thompson
Scraped judge: Kenny Griffis
Scraped judge: Kevin Brobson
Scraped judge: Kevin M. Dougherty
Scraped judge: Kevin Patrick Yeary
Scraped judge: Keynen “KJ” Wall Jr.
Scraped judge: Kimberly Ann Thomas
Scraped judge: Kimberly S. Budd
Scraped judge: Kristina Pickering
Scraped judge: Kyle D. Hawkins
Scraped judge: Kyra Harris Bolden
Scraped judge: Larkin Walsh
Scraped judge: Laurie McKinnon
Scraped judge: Lee Finley “Gary”
Scraped judge: Leondra R. Kruger
Scraped judge: Leslie D. King
Scraped judge: Letitia Verdin
Scraped judge: Lidia S. Stiglich
Scraped judge: Linda M. Bell
Scraped judge: Lisa Fair McEvers
Scraped judge: Lisa Ginoza
Scraped judge: Lisa Holder White
Scraped judge: Loretta H. Rush
Scraped judge: Lynne Boomgaarden
Scraped judge: M. John Kane, IV
Scraped judge: Madeline Singas
Scraped judge: Maria E. Berkenkotter
Scraped judge: Maria Elena Cruz
Scraped judge: Mark E. Salter
Scraped judge: Mark S Massa
Scraped judge: Marla Luckert
Scraped judge: Mary Kay O’Brien
Scraped judge: Mary L. Wagner
Scraped judge: Mary Lou Keel
Scraped judge: Mary R. Russell
Scraped judge: Matthew B. Durrant
Scraped judge: Matthew Fader
Scraped judge: Matthew McDermott
Scraped judge: Maureen McKenna Goldberg
Scraped judge: Meagan Aileen Flynn
Scraped judge: Megan K. Cavanagh
Scraped judge: Megan Shanahan
Scraped judge: Melissa A. Long
Scraped judge: Melissa Beth Countway
Scraped judge: Melissa Taylor Standridge
Scraped judge: Meredith Sasso
Scraped judge: Michael E. Vigil
Scraped judge: Michael J. Garcia
Scraped judge: Michael K. Randolph
Scraped judge: Michael Noriega
Scraped judge: Michael P. Drescher
Scraped judge: Michelle M. Keller
Scraped judge: Monica M. Márquez
Scraped judge: N. Christopher Griffiths
Scraped judge: Nancy Waples
Scraped judge: Natalie E. Hudson
Scraped judge: Nels S.D. Peterson
Scraped judge: Noma Diane Gurich
Scraped judge: Nora Dannehy
Scraped judge: P. Scott Neville, Jr.
Scraped judge: Paige Petersen
Scraped judge: Pamela R. Goodwine
Scraped judge: Patricia Guerrero
Scraped judge: Patricia J. DeVaney
Scraped judge: Patricia Lee
Scraped judge: Patrick E. Donovan
Scraped judge: Patrick F. Fischer
Scraped judge: Paul A. Suttell
Scraped judge: Paul C. Thissen
Scraped judge: Paul C. Wilson
Scraped judge: Paul L. Reiber
Scraped judge: Paul Newby
Scraped judge: Peter K. Killough
Scraped judge: Philip Berger Jr.
Scraped judge: Piper D. Griffin
Scraped judge: R. Patrick DeWine
Scraped judge: Rachel Wainer-Apter
Scraped judge: Raheem L. Mullins
Scraped judge: Raquel Montoya-Lewis
Scraped judge: Rebeca Aizpuru Huddle
Scraped judge: Rebecca Duncan
Scraped judge: Rebecca Frank Dallet
Scraped judge: Rebecca Grassl Bradley
Scraped judge: Renatha Francis
Scraped judge: Rhonda K. Wood
Scraped judge: Richard Bernstein
Scraped judge: Richard Darby
Scraped judge: Richard Dietz
Scraped judge: Richard L. Gabriel
Scraped judge: Rick Lawrence
Scraped judge: Robert B. Conley
Scraped judge: Robert Gusinsky
Scraped judge: Robert Hudson
Scraped judge: Robert Jarosh
Scraped judge: Robert P. Chamberlin
Scraped judge: Robin Ransom
Scraped judge: Robyn M. Brody
Scraped judge: Roger DeHoog
Scraped judge: Ron D. Parraguirre
Scraped judge: Rowan D. Wilson
Scraped judge: Roy W. McLeese
Scraped judge: Sabrina S. McKenna
Scraped judge: Sal Mungia
Scraped judge: Sallie Updyke Mundy
Scraped judge: Sanjay T. Tailor
Scraped judge: Sarah H. Stewart
Scraped judge: Sarah Hawkins Warren
Scraped judge: Sarah Hennesy
Scraped judge: Sarah Keeton Campbell
Scraped judge: Scott L. Kafker
Scraped judge: Scott P. Myren
Scraped judge: Scott Rowland
Scraped judge: Scott Walker
Scraped judge: Serge Georges, Jr.
Scraped judge: Sharon L. Kennedy
Scraped judge: Shawn A. Womack
Scraped judge: Shawn Ellen LaGrua
Scraped judge: Sheryl Gordon McCloud
Scraped judge: Shirley M. Watts
Scraped judge: Shirley Troutman
Scraped judge: Stephanie F. Stacy
Scraped judge: Stephen Bushong
Scraped judge: Stephen R.
McCullough
Scraped judge: Steven A. González
Scraped judge: Steven B. Gould
Scraped judge: Steven D. Ecker
Scraped judge: Steven R. Jensen
Scraped judge: Stuart Rabner
Scraped judge: Susan Christensen
Scraped judge: Susan Crawford
Scraped judge: Susan M. Carney
Scraped judge: Tamara Barringer
Scraped judge: Teresa M. Chafin
Scraped judge: Theodora Gaitas
Scraped judge: Thomas D. Waterman
Scraped judge: Thomas Ewing
Scraped judge: Thomas Mann
Scraped judge: Todd W. Eddins
Scraped judge: Tommy Bryan
Scraped judge: Travis Jett
Scraped judge: Trey Allen
Scraped judge: Valerie Stanfill
Scraped judge: Verda M. Colvin
Scraped judge: Vijay Shanker
Scraped judge: Vladimir Devens
Scraped judge: W. Brent Powell
Scraped judge: Wayne Douglas
Scraped judge: Wesley G. Russell Jr.
Scraped judge: Will Parker
Scraped judge: William B. Cassel
Scraped judge: William B. Sellers
Scraped judge: William G. Montgomery
Scraped judge: William H. Bright, Jr.
Scraped judge: William J. Musseman, Jr.
Scraped judge: William P. Robinson III
Scraped judge: William R. Wooton
Scraped judge: William W. Hood, III
Scraped judge: Zel M. Fischer

,JID,name,state,gender,party,race,professional experience,election type,term start,term end,next election date
0,eb887c0e-f844-484a-bb86-42442231e877,Abigail LeGrow,DE,female,unsure,white,"corporate, judicial","appointed, leg confirmed","may 3, 2023",2035,requires re-nomination and re-confirmation
1,3e411aa7-15d0-41ba-b822-c977aeb3407a,Adam Tanenbaum,FL,male,republican,white,"government civil (non civil rights), judicial,...",appointed,"january 14, 2026","january 2, 2029",<NA>
2,0e46adc7-982e-48f2-ba90-8a5f7739707c,Aimee A. Oravec,AK,female,unsure,white,"corporate, misc. private practice",appointed,"january 31, 2025",2028,2028
3,74cf0c52-33b0-4fa8-84dc-3cd15f1a62b2,Alisa Kelli Wise,AL,female,republican,white,"corporate, misc. private practice, judicial, o...","elected, partisan",2011,"january 15, 2029","november 2, 2028"
4,8791a09e-321b-4a30-95d8-56588932b423,Allison Riggs,NC,female,democrat,white,"legal aid/non-govt civil rights, judicial",appointed,"september 11, 2023","december 31, 2024","november 7, 2024"
...,...,...,...,...,...,...,...,...,...,...,...
340,c7fb3196-9702-4565-abcf-eaa21a0869e2,"William J. Musseman, Jr.",OK,male,republican,white,"prosecutor, judicial",appointed,2022,unsure,unsure
341,200a7b12-a9c1-4c66-a275-b50f39696f89,William P. Robinson III,RI,male,republican,white,misc. private practice,"appointed, leg confirmed",2004,lifetime,n/a - appointed for life
342,95044e43-7ecd-42fc-a881-ec227f247d47,William R. Wooton,WV,male,democrat,white,"prosecutor, plaintiff-side civil private pract...","elected, nonpartisan","january 1, 2021",december 2032,tbd
343,81f897ec-21e1-4222-857f-4c2afb5c173f,"William W. Hood, III",CO,male,democrat,white,"prosecutor, corporate, plaintiff-side civil pr...","appointed, retention elected","january 13, 2014","january 11, 2027","november 3, 2026"
344,2ba65149-f6e9-49eb-b0ce-70052a4a8c1d,Zel M. Fischer,MO,male,republican,white,"misc. private practice, judicial","appointed, retention elected",2008,"december 31, 2034","november 7, 2034"

In [22]:
judge_pd[judge_pd["state"] == "LA"]

,JID,name,state,gender,party,race,professional experience,election type,term start,term end,next election date
34,fb3b4e4d-083f-43df-8c80-f0aa88a7fc9b,Cade Cole,LA,male,republican,white,"prosecutor, government civil (non civil rights...","elected, partisan",march 2025,"december 31, 2026","november 3, 2026"
139,60091a4a-11cd-47fa-a338-a2394de3878f,Jay B. McCallum,LA,male,republican,white,"prosecutor, public defender/other indigent def...","elected, partisan",november 2020,"december 31, 2026","november 3, 2026"
140,895161fe-028f-4481-8abd-d598cb0a761f,Jefferson D. Hughes III,LA,male,republican,white,"misc. private practice, judicial","elected, partisan",february 2013,"december 31, 2028","november 7, 2028"
155,48bacdca-711a-4830-86fc-9c00a180f65a,John Guidry,LA,male,democrat,black,"judicial, legislative experience","elected, partisan","january 1, 2025",<NA>,<NA>
158,c2f8d79a-2170-4d5e-8d7f-1af544a44d99,John L. Weimer,LA,male,independent,white,"misc. private practice, judicial, law professo...","elected, partisan",2001,"december 31, 2032","november 2, 2032"
261,2e1df48f-ebed-43b5-b5c1-2d86d1c7dc71,Piper D. Griffin,LA,female,democrat,black,"misc. private practice, judicial","elected, partisan","january 1, 2021","december 31, 2030","november 5, 2030"